apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 148761640527.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
        ports:
        - containerPort: 3000
