name: Full EKS Infra + App + Monitoring Deployment

on:
  workflow_dispatch: # Manual trigger for setup tasks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl, eksctl, helm
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl && sudo mv kubectl /usr/local/bin/

        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin/

        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Create EKS cluster (one-time)
      run: |
        eksctl create cluster \
          --name nodejs-cluster \
          --region us-east-1 \
          --nodes 2 \
          --managed

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name nodejs-cluster --region us-east-1

    - name: Apply Node.js app manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Install Prometheus + Grafana via Helm
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

        kubectl create namespace monitoring || true

        helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring
